# Generated by Django 6.0.7 on 2026-07-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_rating_product_reviews_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='installment_months',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
